name: inventory-ms

services:
  mongo:
    image: mongo:7
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.runCommand({ ping: 1 })']
      interval: 5s
      timeout: 5s
      retries: 20

  mongo-rs-init:
    image: mongo:7
    depends_on:
      - mongo
    volumes:
      - ../mongo/init-replica-set.sh:/init-replica-set.sh:ro
    entrypoint: ['bash', '/init-replica-set.sh']
    restart: 'no'

  redis:
    image: redis:7-alpine
    command: ['redis-server', '--save', '', '--appendonly', 'no']
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 20

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'

  minio:
    image: minio/minio:latest
    command: ['server', '/data', '--console-address', ':9001']
    environment:
      MINIO_ROOT_USER: localminio
      MINIO_ROOT_PASSWORD: localminiosecret
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mongo-data:
  minio-data:
